### PR TITLE
Breaking changes for 2.0

### LINKED ISSUE #715: Breaking changes in 2.0
Branch: [tido/2.0](https://github.com/microsoft/react-native-test-app/compare/tido/2.0?expand=1)
Timeline: TBD

### Breaking changes

- [x] End support for 0.62, 0.63
- [x] Remove workarounds for 0.62, 0.63
  - See [Patches](https://github.com/microsoft/react-native-test-app/wiki/Patches) for full list
- [ ] ~Should we remove `ReactTestApp.xcscheme`?~ https://github.com/microsoft/react-native-test-app/blob/d3c84d01bbea80b90ee7a835bc3d42d7098643ae/ios/test_app.rb#L166-L167
  - This is still useful for deterministic workspace scheme on CI
- [x] Drop support for Node 12

### PR DESCRIPTION
**Pull request by tido64**
### Description

A collection of breaking changes.

Note: This PR must *not* be squashed before merging.

Resolves #715.

### Platforms affected

- [ ] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows

### Test plan

```
npm run set-react-version 0.64
yarn
cd example
rm ios/Podfile.lock macos/Podfile.lock

# Test Android
yarn android

# Test iOS
pod install --project-directory=ios
yarn ios

# Test macOS
pod install --project-directory=macos
yarn macos

# Test Windows
yarn install-windows-test-app
yarn windows
```

### CODE REVIEW

**Comment by Saadnajmi** [comment]
Can't find the original issue, but something something remove duplicate xcscheme was one for 2.0 as well?

image

**Comment by tido64** [comment]
> Can't find the original issue, but something something remove duplicate xcscheme was one for 2.0 as well?

#715 lists it. I wanted to keep it since it helps with scripting. Faster to use ReactTestApp as scheme than running `xcodebuild -list` and parsing the output. Happy to be convinced otherwise. Is this breaking anything on your side?

**Comment by Saadnajmi** [comment]
Nah, I was thinking similarly. I didn't have a strong want to remove it besides redundancy.If we still wanted to remove redundancy and instead removed the scheme whose name matched the test app name, that would be a relatively easy breaking change to handle for us anyway. But I don't have a strong opinion either way.

**Review by kelset — COMMENTED** [review]
Overall, the changes LGTM.

I did some local testing following the steps in the PR body.

* Android works fine ✅
* macos works fine ✅
* can't test windows 🍎
* for iOS, I hit an issue on the pod install step:
```
`LoadError - dlopen(<REDACTED>/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried: '<REDACTED>/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e))) - <REDACTED>/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ffi-1.15.5/lib/ffi_c.bundle`
```
I'm going to try understanding what's causing it, I even tried using at the [M1 pod workaround](https://reactnative.dev/docs/next/environment-setup#cocoapods) but didn't help. I feel it might just be related to the version of Ruby used, will investigate more

**Comment by kelset** [comment]
update: fixed my iOS problem, managed to test iOS just fine ✅

last bit missing is testing on Windows but I can't help with that

**Review by kelset — APPROVED** [review]

**Comment by tido64** [comment]
I ran a last check on Windows to be sure:
image

**Pull request merged**
