### PR TITLE
feat: add ability to set app icons

### LINKED ISSUE #242: Android: Use the library launcher icon if available instead of react-native-test-app default

### LINKED ISSUE #990: mechanism to set app icon, app version
### Proposal

As far as I can tell, there isn't an existing way to specify/provide an app icon.   On iOS (my primary target) the installed app uses the default icon provided by XCode.

It would be nice to be able to specify the path to an icon in the app.json manifest, and have that be used.

Similarly I don't see a way to specify the app version.   On iOS this is stored in the info.plist file, which is part of the react-native-test-app dependency.   Not being able to change the version number makes it difficult to make builds that can be uploaded to TestFlight for distribution.

It would be nice to be able to specify the app version in the app.json manifest.

### Alternatives

n/a

### Implementation Details

n/a

### Additional Context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tido64**
### Description

Adds ability to set app icons.

iOS/macOS has the ability to set alternate icons. I've made affordances for it here, but will be implementing the actual support separately: #1023

Resolves #242.
Resolves #990.

### Platforms affected

- [x] Android
- [x] iOS
- [x] macOS
- [ ] Windows

### Test plan

```diff
diff --git a/example/app.json b/example/app.json
index ef69fa7..3fdf9e6 100644
--- a/example/app.json
+++ b/example/app.json
@@ -13,6 +13,25 @@
       "presentationStyle": "modal"
     }
   ],
+  "android": {
+    "icons": "android/res-launcher"
+  },
+  "ios": {
+    "icons": {
+      "primaryIcon": {
+        "filename": "WindowsPhone.png",
+        "prerendered": true
+      }
+    }
+  },
+  "macos": {
+    "icons": {
+      "primaryIcon": {
+        "filename": "WindowsPhone.png",
+        "prerendered": true
+      }
+    }
+  },
   "resources": {
     "android": [
       "dist/res",
```

### Screenshots

| Android | iOS | macOS |
| :-: | :-: | :-: |
| Screenshot_1658762014 | Simulator Screen Shot - iPhone 13 - 2022-07-25 at 17 15 43 | image |

### CODE REVIEW

**Comment by kelset** [comment]
tried to test it locally, and Android and iOS work fine - for some reason macos doesn't seem to work though (check icon in dock):

Screenshot 2022-07-27 at 15 57 16

I followed the repro steps + the ones from [here for testing macos](https://github.com/microsoft/react-native-test-app/blob/trunk/CONTRIBUTING.md#macos) so I'm not sure if I'm doing something wrong?

**Comment by tido64** [comment]
> for some reason macos doesn't seem to work though (check icon in dock):

That is odd. I tried from a clean branch and got the icon:

image

Can you try cleaning out DerivedData (⇧⌘K) and rebuild?

**Comment by tido64** [comment]
Also, can you check if the assets catalog is correctly populated:

image

**Review by kelset — APPROVED** [review]
after a bunch of local testing we figured out it was something with my local caching... it works fine now! Let's :shipit:

**Pull request merged**
