### PR TITLE
fix(windows): `metro.config.windows.js` is no longer needed

### PR DESCRIPTION
**Pull request by tido64**
### Description

It hasn't been needed since `@react-native-community/cli` [v4.9.0](https://github.com/react-native-community/cli/commit/b92fbc6b9b30f08486b75a9f40d78d364249ccb8).

### Platforms affected

- [ ] Android
- [ ] iOS
- [ ] macOS
- [x] Windows

### Test plan

```
cd example
yarn
yarn install-windows-test-app --use-nuget
start windows/Example.sln
yarn start
```

The test app should successfully load from the dev server.

### CODE REVIEW

**Comment by tido64** [comment]
cc @Saadnajmi

**Comment by Saadnajmi** [comment]
You don't need to specify a `npmPackageName` in your metro config for react-native-windows?
https://github.com/react-native-community/cli/blob/master/docs/platforms.md#npmpackagename

**Comment by tido64** [comment]
> You don't need to specify a `npmPackageName` in your metro config for react-native-windows?
> https://github.com/react-native-community/cli/blob/master/docs/platforms.md#npmpackagename

No, that field is for out-of-platform packages, i.e. [`react-native-macos`](https://github.com/microsoft/react-native-macos/blob/415abb553e33e93586e7c74a36f8eddb0266dc6d/react-native.config.js#L67) and [`react-native-windows`](https://github.com/microsoft/react-native-windows/blob/b7da9b7b910ee38853a4afdcdbad4afde9ab6958/vnext/react-native.config.js#L14).

**Comment by Saadnajmi** [comment]
> > You don't need to specify a `npmPackageName` in your metro config for react-native-windows?
> > https://github.com/react-native-community/cli/blob/master/docs/platforms.md#npmpackagename
> 
> No, that field is for out-of-platform packages, i.e. [`react-native-macos`](https://github.com/microsoft/react-native-macos/blob/415abb553e33e93586e7c74a36f8eddb0266dc6d/react-native.config.js#L67) and [`react-native-windows`](https://github.com/microsoft/react-native-windows/blob/b7da9b7b910ee38853a4afdcdbad4afde9ab6958/vnext/react-native.config.js#L14).

Right, but doesn't the example test app being updated here support both windows and macOS? ergo, wouldn't we need to fill that field out somewhere? I'm probably understanding the change wrong.

**Comment by tido64** [comment]
> > > You don't need to specify a `npmPackageName` in your metro config for react-native-windows?
> > > https://github.com/react-native-community/cli/blob/master/docs/platforms.md#npmpackagename
> > 
> > 
> > No, that field is for out-of-platform packages, i.e. [`react-native-macos`](https://github.com/microsoft/react-native-macos/blob/415abb553e33e93586e7c74a36f8eddb0266dc6d/react-native.config.js#L67) and [`react-native-windows`](https://github.com/microsoft/react-native-windows/blob/b7da9b7b910ee38853a4afdcdbad4afde9ab6958/vnext/react-native.config.js#L14).
> 
> Right, but doesn't the example test app being updated here support both windows and macOS? ergo, wouldn't we need to fill that field out somewhere? I'm probably understanding the change wrong.

No, the field is only for platform providers. Consumers don't need to do anything.

**Review by kelset — APPROVED** [review]

**Pull request merged**
