### PR TITLE
fix: use app display name from the manifest

### PR DESCRIPTION
**Pull request by tido64**
### Description

The test app currently doesn't use `displayName` from the manifest at all and just installs itself as `ReactTestApp`.

### Platforms affected

- [x] Android
- [x] iOS
- [x] macOS
- [ ] Windows

### Test plan

| Android |   iOS   |
|:-------:|:-------:|
| Screenshot_1612388614 | Simulator Screen Shot - iPhone 12 Pro - 2021-02-03 at 22 43 35 |

### CODE REVIEW

**Comment by tido64** [comment]
cc @sveinar

**Review by sweggersen — APPROVED** [review]

**Comment by sveinar** [comment]
Fantastic good job, loving it!

**Comment by Saadnajmi** [comment]
Just curious: Is this not done on windows, did windows already use the display name, or is it not possible on windows?

**Comment by tido64** [comment]
@Saadnajmi: There's this idea of being able to provide your own `.appxmanifest` (#224). Since the display name is in the same file, I didn't want to make any Windows changes in this PR.

**Pull request merged**
