### PR TITLE
macOS: Add Plop template

### LINKED ISSUE #88: Add macOS target to Plop template
Requires #87

- [x] Add template macOS targets to CI

### PR DESCRIPTION
**Pull request by tido64**
Resolves #88.

### CODE REVIEW

**Comment by alloy** [comment]
This isn’t part of this PR, but why should the user install Plop separately? https://github.com/microsoft/react-native-test-app/blob/2a1cfd6f268cd1539601c035a3ca45cb89aa8d59/README.md#quick-start

**Comment by tido64** [comment]
> 
> 
> This isn’t part of this PR, but why should the user install Plop separately? https://github.com/microsoft/react-native-test-app/blob/2a1cfd6f268cd1539601c035a3ca45cb89aa8d59/README.md#quick-start

Tbh, I'm just following the documentation: https://plopjs.com/documentation/#installation. But on closer inspection, that may be for template devs and not for consumers. I'll check if using `npx` is enough, and update the instructions.

**Comment by alloy** [comment]
Noticing this deprecation warning, is that on your radar?

```
[!] Passing custom root to use_native_modules! is deprecated.
    - CLI detects root of the project automatically. The "." argument was ignored.
```

**Comment by tido64** [comment]
> Noticing this deprecation warning, is that on your radar?
> 
> ```
> [!] Passing custom root to use_native_modules! is deprecated.
>     - CLI detects root of the project automatically. The "." argument was ignored.
> ```

Yup, addressed here: https://github.com/microsoft/react-native-test-app/pull/17/files#diff-ccb88c6fbd1a6787a22c613fbff1b980

**Comment by alloy** [comment]
> Tbh, I'm just following the documentation: https://plopjs.com/documentation/#installation. But on closer inspection, that may be for template devs and not for consumers. I'll check if using `npx` is enough, and update the instructions.

It’s not immediately clear to me what scenario they describe there, but for our case making Plop a runtime dependency and instructing users to install `react-native-test-app` as a dev dependency should be enough imo.

**Comment by alloy** [comment]
Was able to build the macOS app, given the included instructions :+1:

**Comment by tido64** [comment]
> Was able to build the macOS app, given the included instructions +1

Thanks for the thorough review :heart:

**Comment by alloy** [comment]
You got it, buddy!

**Pull request merged**
