### PR TITLE
ci(apple): Use macOS 13 XL images

### PR DESCRIPTION
**Pull request by Saadnajmi**
### Description

Use macOS 13 XL images

### Platforms affected

- [ ] Android
- [x] iOS
- [x] macOS
- [ ] Windows

### Test plan

Ci should pass.. faster

### CODE REVIEW

**Comment by tido64** [comment]
| `macos-13` | `macos-13-xl` | `macos-13-xlarge` |
| :-: | :-: | :-: |
| image | image | image |

🤤

**Review by kelset — APPROVED** [review]

**Comment by tido64** [comment]
With the XL images, we are now incurring billable time. I think we need to check whether this is okay:

image

**Comment by kelset** [comment]
oh that's a good shout, let me remove my review so that we don't merge until we have clarity on that

**Review by kelset — CHANGES_REQUESTED** [review]
blocking until we have clarity on billable time

**Comment by tido64** [comment]
Followed up internally and got the message that we're not supposed to be using these. Closing.

**Pull request closed without merging**
