### PR TITLE
chore(iOS): Remove traces of CocoaPods from source Xcode project

### PR DESCRIPTION
**Pull request by tido64**
Without this, Xcode will consistently crash when trying to expand project configuration, e.g. `Release` as in the screenshot below.

image

Others seem to have hit this issue as well: https://developer.apple.com/forums/thread/130202

### CODE REVIEW

**Comment by alloy** [comment]
So these are unused references? Little hard to tell just from the pbxproj diff.

**Comment by tido64** [comment]
> So these are unused references? Little hard to tell just from the pbxproj diff.

Yeah, I just used `pod deintegrate` to clean up the pbxproj. They get re-added when used anyway.

**Comment by alloy** [comment]
@NeoNacho Is this issue on your radar? (Pun intended)

**Pull request merged**
